# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Java CI test with Maven


on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  build-and-test-backend:
  
    runs-on: ubuntu-latest

    steps:

      - name: Code Checkout 
        uses: actions/checkout@v4

     
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' 
          cache: 'maven'

     
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: target/*.jar

  deploy-backend:
    
   
    needs: build-and-test-backend
    
    
    if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') && github.event_name == 'push'
    
    runs-on: ubuntu-latest

    steps:
      # Download of job1 artifacts
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build 
          path: deploy-package # Temporary folder 
        
     
      #There is no deploys yet.

